#!/bin/bash
 
#checking sudo rights
if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

#stop virtual RAID disk
sudo mdadm --stop --scan
sudo losetup --detach-all

#remove temporary pid file
sudo rm /tmp/qemu-win.pid

exit
